spring:
  application:
    name: vue-element-admin-java-api
  datasource:
    username: root
    password: toor
    url: jdbc:mysql://localhost:3306/vue_element_admin_prod_db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    initialization-mode: never
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: mysql
    open-in-view: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  servlet:
    context-path: /prod-api
  port: 8080

com:
  xingyun:
    vue:
      element:
        admin:
          adminUserName: admin
          adminUserPassword: 111111
          editorUserName: editor
          editorUserPassword: 111111

management:
  endpoint:
    health:
      show-details: when_authorized
