spring:
  application:
    name: vue-element-admin-java-api
  datasource:
    username: sa
    password: sa
    # base on file
    #url: jdbc:h2:~/embedded_file_test_db
    #base on memory
    url: jdbc:h2:mem:vue_element_admin_db;DB_CLOSE_DELAY=-1
    initialization-mode: never
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database: h2
    open-in-view: true
    show-sql: true
management:
  endpoint:
    health:
      show-details: when_authorized


server:
  servlet:
    context-path: /dev-api
  port: 8080
com:
  xingyun:
    vue:
      element:
        admin:
          adminUserName: admin
          adminUserPassword: 111111
          editorUserName: editor
          editorUserPassword: 111111